# Action metadata file:
# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file

name: 'xelatex Lecture week'
description: 'Runs xelatex on each .tex in a given folder'
inputs:
  folder:
    description: 'Used folder'
    required: true
  mode:
    description: 'Compiling mode. Can be "handout" or non handout'
    required: false
    default: 'animation'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder }}
    - ${{ inputs.mode }}
